//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.net.paulofernando.pessoasinspiradoras;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import br.net.paulofernando.pessoasinspiradoras.R.id;
import br.net.paulofernando.pessoasinspiradoras.R.layout;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class AddPersonActivity_
    extends AddPersonActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_add_person);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        photo = ((ImageView) findViewById(id.add_person_photo));
        etPersonName = ((EditText) findViewById(id.et_add_person_name));
        {
            View view = findViewById(id.bt_add_cancel);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddPersonActivity_.this.cancelSettings();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.add_person_photo);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddPersonActivity_.this.changePhoto();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.bt_add_save);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AddPersonActivity_.this.save();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static AddPersonActivity_.IntentBuilder_ intent(Context context) {
        return new AddPersonActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AddPersonActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AddPersonActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
