//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.net.paulofernando.pessoasinspiradoras.view;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import br.net.paulofernando.pessoasinspiradoras.R.id;
import br.net.paulofernando.pessoasinspiradoras.R.layout;
import br.net.paulofernando.pessoasinspiradoras.model.ImportEntity;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ImportInspirationsView_
    extends ImportInspirationsView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public ImportInspirationsView_(Context context) {
        super(context);
        init_();
    }

    public ImportInspirationsView_(ImportEntity importPerson, Context context) {
        super(importPerson, context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        amountInspirations = ((TextView) findViewById(id.person_amount_inspirations_import));
        personName = ((TextView) findViewById(id.person_name_import));
        mergeIcon = ((ImageView) findViewById(id.merge_icon));
        check = ((CheckBox) findViewById(id.check_import));
        componentImportView = ((RelativeLayout) findViewById(id.componentImportView));
        {
            View view = findViewById(id.componentPersonView);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ImportInspirationsView_.this.click();
                    }

                }
                );
            }
        }
        init();
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.view_import_inspirations, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static ImportInspirationsView build(Context context) {
        ImportInspirationsView_ instance = new ImportInspirationsView_(context);
        instance.onFinishInflate();
        return instance;
    }

    public static ImportInspirationsView build(ImportEntity importPerson, Context context) {
        ImportInspirationsView_ instance = new ImportInspirationsView_(importPerson, context);
        instance.onFinishInflate();
        return instance;
    }

}
