//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.net.paulofernando.pessoasinspiradoras.view;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import br.net.paulofernando.pessoasinspiradoras.R.id;
import br.net.paulofernando.pessoasinspiradoras.R.layout;
import br.net.paulofernando.pessoasinspiradoras.model.PersonEntity;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class PersonView_
    extends PersonView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public PersonView_(Context context) {
        super(context);
        init_();
    }

    public PersonView_(PersonEntity person, Context context) {
        super(person, context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        medalha = ((ImageView) findViewById(id.medalha));
        photo = ((ImageView) findViewById(id.photo));
        personName = ((TextView) findViewById(id.person_name));
        componentPersonView = ((RelativeLayout) findViewById(id.componentPersonView));
        amountInspirations = ((TextView) findViewById(id.person_amount_inspirations));
        {
            View view = findViewById(id.componentPersonView);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PersonView_.this.click();
                    }

                }
                );
            }
        }
        init();
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.view_person, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static PersonView build(Context context) {
        PersonView_ instance = new PersonView_(context);
        instance.onFinishInflate();
        return instance;
    }

    public static PersonView build(PersonEntity person, Context context) {
        PersonView_ instance = new PersonView_(person, context);
        instance.onFinishInflate();
        return instance;
    }

}
